spring:
  data:
    mongodb:
      uri: mongodb://sds:sds@mongodb:27017/mysds?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sds